apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nodejs-dashboard-shuja"
  description: "nothing special"
  annotations:
    github.com/project-slug: user:default/shujaahmedi2l/nodejs-dashboard-shuja
    argocd/app-name: nodejs-dashboard-shuja
  links:
    - url: https://dasboard-shuja.onexidp.com
      title: Web Application
      icon: LaunchIcon
spec:
  type: service
  owner: guests
  lifecycle: experimental
